### ISSUE TITLE
Transparent shadows

### ISSUE THREAD

**Issue by buvk** [PARTYMANX/partymod-thps3#1]
Hi there.  I was wondering if it would be possible to correct shadows so that they are transparent/soft.  Thanks.

**Comment by PARTYMANX** [comment]
I looked into it a tiny bit.  it's probably possible but I wasn't able to track down exactly where the shadow rendering is.  if I come back to working on this, it's something on my list.

**Comment by PARTYMANX** [comment]
I've been thinking about this more and wanted to write down my thoughts before I forget: The PS2 version has debug symbols, which would make finding the correct rendering logic pretty easy.  I should find the rendering portion of that code and copy its operations over to the PC version, given that the Renderware functionality is reasonably identical.

**Comment by PARTYMANX** [comment]
Update on that: the PS2 version doesn't have debug symbols.  the resource on the internet saying it does actually means the included Shaun Palmer's Pro Snowboarder demo.

**Comment by PARTYMANX** [comment]
Addressed in latest commit for 1.1.0

**Comment by buvk** [comment]
@PARTYMANX are the shadows supposed to scale with the resolution?

**Comment by PARTYMANX** [comment]
In that the shadows increase resolution as resolution increase?  they aren't intended to.

**Comment by buvk** [comment]
Ah ok, I was just curious because shadows appear quite jaggy even when resolution is set to something like 4K.
