### ISSUE TITLE
Support for exes with different checksums

### ISSUE THREAD

**Issue by buvk** [PARTYMANX/partymod-thps3#22]
partypatcher for THPS4 supports the -f parameter to force the patch to be applied if the executable is of the right size.  Would it be possible to implement a similar feature for partypatcher for THPS3?

**Comment by PARTYMANX** [comment]
this was always in the back of my mind as something that should probably be there but no one had mentioned it yet so I just never added it lol.  Really, all of the patchers should be a bit closer in functionality.  I'll add it soon

**Comment by PARTYMANX** [comment]
finally fixed.  unrecognized checksums are notified, but don't result in failure.
