### ISSUE TITLE
Pressing the Confirm Button via Controller on the Menu rapidly goes through Menu.

### ISSUE THREAD

**Issue by NikkoNikkoYeet** [PARTYMANX/partymod-thps3#6]
Title is self explanatory but yeah navigating menus with the Controller is... Quite a difficult task.  Just a single press of a button and it goes through menus quick. 

EDIT: The Start Button is also applied to this issue. Can't pause with a controller.

**Comment by PARTYMANX** [comment]
This sounds a lot like a problem i was running into when testing yesterday: I had either esc or enter bound to menu and it was doing something similar.  check that you don't have either of those buttons bound to enter via joytokey or steam input.

**Comment by NikkoNikkoYeet** [comment]
I think the latter might be the case. 

I'll go to see closing Steam in the background may work.

**Comment by NikkoNikkoYeet** [comment]
Update: That actually fixed the issue!  Thanks. 

PS: Are there any plans to put Rumble Support for THPS 3?

**Comment by PARTYMANX** [comment]
I'd like to explore it.  the lack of support in the original makes it a bit difficult though.  I'm not sure how much of the original code to support it remains
